import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Robbie' at '11/27/16 1:46 PM' with Gradle 2.14.1
 *
 * @author Robbie, @date 11/27/16 1:46 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        BadgeBook classUnderTest = new BadgeBook();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
